
package org.AirlineSOAPServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FlightDetailsService", targetNamespace = "http://www.example.org/FlightDetailsService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightDetailsService {


    /**
     * 
     * @param flightDetailsGetRequest
     * @return
     *     returns org.AirlineSOAPServices.FlightDetailsGetResponseType
     */
    @WebMethod(action = "http://www.example.org/FlightDetailsService/getFlightDetails")
    @WebResult(name = "flightDetailsGetResponse", targetNamespace = "")
    @RequestWrapper(localName = "getFlightDetails", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.GetFlightDetails")
    @ResponseWrapper(localName = "getFlightDetailsResponse", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.GetFlightDetailsResponse")
    public FlightDetailsGetResponseType getFlightDetails(
        @WebParam(name = "flightDetailsGetRequest", targetNamespace = "")
        FlightDetailsGetRequestType flightDetailsGetRequest);

    /**
     * 
     * @param flightDetailsCreateRequest
     * @return
     *     returns org.AirlineSOAPServices.FlightDetailsCreateResponseType
     */
    @WebMethod(action = "http://www.example.org/FlightDetailsService/createFlightDetails")
    @WebResult(name = "flightDetailsCreateResponse", targetNamespace = "")
    @RequestWrapper(localName = "createFlightDetails", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.CreateFlightDetails")
    @ResponseWrapper(localName = "createFlightDetailsResponse", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.CreateFlightDetailsResponse")
    public FlightDetailsCreateResponseType createFlightDetails(
        @WebParam(name = "flightDetailsCreateRequest", targetNamespace = "")
        FlightDetailsCreateRequestType flightDetailsCreateRequest);

    /**
     * 
     * @param flightDetailsDeleteRequest
     * @return
     *     returns org.AirlineSOAPServices.FlightDetailsDeleteResponseType
     */
    @WebMethod(action = "http://www.example.org/FlightDetailsService/deleteFlightDetails")
    @WebResult(name = "flightDetailsDeleteResponse", targetNamespace = "")
    @RequestWrapper(localName = "deleteFlightDetails", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.DeleteFlightDetails")
    @ResponseWrapper(localName = "deleteFlightDetailsResponse", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.DeleteFlightDetailsResponse")
    public FlightDetailsDeleteResponseType deleteFlightDetails(
        @WebParam(name = "flightDetailsDeleteRequest", targetNamespace = "")
        FlightDetailsDeleteRequestType flightDetailsDeleteRequest);

    /**
     * 
     * @param flightDetailsUpdateRequest
     * @return
     *     returns org.AirlineSOAPServices.FlightDetailsUpdateResponseType
     */
    @WebMethod(action = "http://www.example.org/FlightDetailsService/updateFlightDetails")
    @WebResult(name = "flightDetailsUpdateResponse", targetNamespace = "")
    @RequestWrapper(localName = "updateFlightDetails", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.UpdateFlightDetails")
    @ResponseWrapper(localName = "updateFlightDetailsResponse", targetNamespace = "http://www.example.org/FlightDetailsService/", className = "org.AirlineSOAPServices.UpdateFlightDetailsResponse")
    public FlightDetailsUpdateResponseType updateFlightDetails(
        @WebParam(name = "flightDetailsUpdateRequest", targetNamespace = "")
        FlightDetailsUpdateRequestType flightDetailsUpdateRequest);

}
